# Generated by Django 3.2.7 on 2021-09-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_auto_20210926_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='descrip',
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
