# Generated by Django 3.2.7 on 2021-09-29 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_alter_course_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='video_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
